web1804-php7:
  build: .
  dockerfile: ./1804/Dockerfile
  environment:
    - MYSQL_ADMIN_PASS=password
  ports:
    - "3000:80"
    - "3001:3306"

web1604-php7:
  build: .
  dockerfile: ./1604/Dockerfile
  environment:
    - MYSQL_ADMIN_PASS=password
  ports:
    - "3010:80"
    - "3011:3306"

web1804-php71:
  build: .
  dockerfile: ./1804-php71/Dockerfile
  environment:
    - MYSQL_ADMIN_PASS=password
  ports:
    - "3020:80"
    - "3021:3306"
